version: '3'

services:

  yacs_api:
    container_name: yacs_api
    build:
        context: ./src/api/
        dockerfile: Dockerfile
    tty: true
    ports:
      - 5000:5000
    environment:
      - ENV=production
      - DEBUG=False
      - DB_HOST=yacs_db
      - DB_USER=yacs
      - DB_PASS=yacs_pass
      - DB_NAME=yacs
    expose:
      - 5000
    depends_on:
      - yacs_db

  yacs_db:
    container_name: yacs_db
    build:
      context: ./src/data/
      dockerfile: Dockerfile
    ports:
      - 5432:5432
