version: '3.4'

# web (front-end) depends on api (back-end) depends on (db)
# web -> api -> db [dependency chain]

services:

  yacs_web:
    container_name: yacs_web # makes logs nicer, otherwise would be yacs_web_1, but is yacs_web
    depends_on:
      - yacs_api

  yacs_api:
    container_name: yacs_api
    tty: true
    ports:
      - 5000:5000
    depends_on:
      - yacs_db

  yacs_db:
    container_name: yacs_db
