version: '3'

services: 

  yacs_backend:
    container_name: yacs_backend 
    build: 
        context: ./src
        dockerfile: Dockerfile      
    stdin_open: true
    tty: true
    ports:
      - "5000:5000"
    volumes:
      - ./src:/usr/src

  postgres:
    container_name: yacs_postgres
    build: 
      context: .
      dockerfile: postgres.Dockerfile      
    ports:
      - 5432:5432      