version: '3'

# web (front-end) depends on api (back-end) depends on (db)
# web -> api -> db [dependency chain]

services:

  yacs_web:
    container_name: yacs_web
    build:
      context: ./src/web
      dockerfile: Dockerfile
    ports:
      - 80:80
    expose:
      - 80
    depends_on:
      - yacs_api
    environment:
      - HOST=localhost

  yacs_api:
    container_name: yacs_api
    build:
      context: ./src/api/
      dockerfile: Dockerfile
    tty: true
    restart: always
    ports:
      - 5000:5000
    environment:
      - ENV=production
      - DEBUG=False
      - DB_HOST=yacs_db
      - DB_USER=yacs
      - DB_PASS=${DB_PASS:-easy_dev_pass}
      - DB_NAME=yacs
    expose:
      - 5000
    depends_on:
      - yacs_db

  yacs_db:
    container_name: yacs_db
    build:
      context: ./src/data/
      dockerfile: Dockerfile
    environment:
      - POSTGRES_DB=yacs
      - POSTGRES_USER=yacs
      - POSTGRES_PASSWORD=${DB_PASS:-easy_dev_pass}
    ports:
      - 5432:5432
    expose:
      - 5432
