"""Use course id for selected courses

Revision ID: 11496f2af3f7
Revises: 53f333149502
Create Date: 2020-12-20 04:03:46.898527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11496f2af3f7'
down_revision = '53f333149502'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_course_selection', sa.Column('course_id', sa.TEXT()))
    op.execute("""
        UPDATE student_course_selection
        SET
            course_id = scs_c.id
        FROM student_course_selection as scs
        LEFT JOIN LATERAL (
            SELECT 
                scs.*,
                concat(
                    c.crn, '|', 
                    c.title, '|', 
                    c.min_credits, '|', 
                    c.max_credits, '|', 
                    c.department, '|', 
                    c.level, '|', 
                    extract(month from c.date_start), '|', 
                    extract(day from c.date_start), '|', 
                    extract(year from c.date_start), '|', 
                    extract(month from c.date_end), '|', 
                    extract(day from c.date_end), '|', 
                    extract(year from c.date_end)
                ) AS id 
            FROM course c 
            WHERE 
                scs.semester = c.semester AND
                scs.course_name = concat(c.department, '-', c.level) AND 
                (scs.crn = '-1' OR scs.crn = c.crn) 
            LIMIT 1
        ) scs_c ON true
        WHERE 
            student_course_selection.semester = scs_c.semester AND
            student_course_selection.course_name = scs_c.course_name AND
            (student_course_selection.crn = '-1' OR student_course_selection.crn = scs_c.crn);
    """)
    op.alter_column('student_course_selection', 'course_id', nullable=False)
    op.drop_column('student_course_selection', 'course_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_course_selection', sa.Column('course_name', sa.VARCHAR(length=255), autoincrement=False))
    op.execute("""
        UPDATE student_course_selection
        SET
            course_name = concat(
                split_part(scs.course_id, '|', 5),
                '-',
                split_part(scs.course_id, '|', 6)
            )
        FROM student_course_selection as scs
        WHERE student_course_selection.course_id = scs.course_id;
    """)
    op.alter_column('student_course_selection', 'course_name', nullable=False)
    op.drop_column('student_course_selection', 'course_id')
    # ### end Alembic commands ###
