"""Use course id for selected courses

Revision ID: 11496f2af3f7
Revises: 53f333149502
Create Date: 2020-12-20 04:03:46.898527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11496f2af3f7'
down_revision = '53f333149502'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_course_selection', sa.Column('course_id', sa.TEXT(), nullable=False))
    op.drop_column('student_course_selection', 'course_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_course_selection', sa.Column('course_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('student_course_selection', 'course_id')
    # ### end Alembic commands ###
