"""

Revision ID: 889d858f872f
Revises: a3be4710680d
Create Date: 2021-08-12 15:54:09.431896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '889d858f872f'
down_revision = 'a3be4710680d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('course_instructor', sa.TEXT(), nullable=True))
    op.add_column('course', sa.Column('email', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'email')
    op.drop_column('course', 'course_instructor')
    # ### end Alembic commands ###
