"""add major

Revision ID: 9d733c5c36e1
Revises: 54df4fb8dfe9
Create Date: 2022-10-11 21:36:42.704022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d733c5c36e1'
down_revision = '54df4fb8dfe9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('major_list',
    sa.Column('major', sa.TEXT(), nullable=False),
    sa.Column('b', sa.BOOLEAN(), nullable=True),
    sa.Column('m', sa.BOOLEAN(), nullable=True),
    sa.Column('d', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('major')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('major_list')
    # ### end Alembic commands ###
