"""Add majorTemplates

Revision ID: a94f358c0128
Revises: 54df4fb8dfe9
Create Date: 2022-03-29 20:31:07.691697

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a94f358c0128'
down_revision = '54df4fb8dfe9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('majorTemplates',
    sa.Column('Major', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('Year', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('Semester', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('Courses', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('Major', 'Year', 'Semester', name='majorTemplates_pkey')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('majorTemplates')
    # ### end Alembic commands ###
