"""Courses table

Revision ID: abcdabcd12345678
Revises: 85de5f210bb7
Create Date: 2023-04-06 00:55:10.389370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abcdabcd12345678'  # randomly created an 'unique id' with 12 hex characters
down_revision = '85de5f210bb7'  # grab value from previous version file
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('courses',
    sa.Column('course_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('course_code', sa.INT, nullable=False),
    sa.Column('dept_code', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('course_name'),
    sa.PrimaryKeyConstraint('course_code'),
    sa.PrimaryKeyConstraint('dept_code')
    )


# def downgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_table('professor')
    # ### end Alembic commands ###
