"""Courses table

Revision ID: abcd12345678
Revises: 85de5f210bb7
Create Date: 2023-04-06 00:55:10.389370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abcd12345678'  # randomly created an 'unique id' with 12 hex characters
down_revision = '12ab3c456dd7'  # grab value from previous version file
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('pathway_courses',
    sa.Column('dept_code', sa.VARCHAR(length=4), nullable=False),
    sa.Column('course_code', sa.VARCHAR(length=4), nullable=False),
    sa.Column('course_name', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('dept_code', 'course_code', 'course_name'),
    )


# def downgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_table('professor')
    # ### end Alembic commands ###
