"""Professor_table

Revision ID: 95cb2a021aa9
Revises: 54df4fb8dfe9
Create Date: 2023-04-06 00:55:10.389370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12ab3c456dd7' #so far, just randomly created an 'unique id' with 12 hex characters
down_revision = '85de5f210bb7' #grab value from previous version file
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('pathway_category',
    sa.Column('category_name', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('category_name')
    )


# def downgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_table('professor')
    # ### end Alembic commands ###
