"""fix professor column names

Revision ID: c959c263997f
Revises: c0289fddf6dd
Create Date: 2023-11-10 22:18:36.674812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c959c263997f'
down_revision = 'c0289fddf6dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professor', sa.Column('department', sa.VARCHAR(length=255), nullable=True))
    op.add_column('professor', sa.Column('email', sa.VARCHAR(length=255), nullable=False))
    op.add_column('professor', sa.Column('name', sa.VARCHAR(length=255), nullable=True))
    op.add_column('professor', sa.Column('phone_number', sa.VARCHAR(length=255), nullable=True))
    op.add_column('professor', sa.Column('portfolio_page', sa.VARCHAR(length=255), nullable=True))
    op.add_column('professor', sa.Column('profile_page', sa.VARCHAR(length=255), nullable=True))
    op.add_column('professor', sa.Column('title', sa.VARCHAR(length=255), nullable=True))
    op.drop_column('professor', 'Phone_number')
    op.drop_column('professor', 'Portfolio_page')
    op.drop_column('professor', 'Name')
    op.drop_column('professor', 'Email')
    op.drop_column('professor', 'Profile_page')
    op.drop_column('professor', 'Department')
    op.drop_column('professor', 'Title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professor', sa.Column('Title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('professor', sa.Column('Department', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('professor', sa.Column('Profile_page', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('professor', sa.Column('Email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('professor', sa.Column('Name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('professor', sa.Column('Portfolio_page', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('professor', sa.Column('Phone_number', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('professor', 'title')
    op.drop_column('professor', 'profile_page')
    op.drop_column('professor', 'portfolio_page')
    op.drop_column('professor', 'phone_number')
    op.drop_column('professor', 'name')
    op.drop_column('professor', 'email')
    op.drop_column('professor', 'department')
    # ### end Alembic commands ###
