"""created finals table

Revision ID: 5141beedaf6c
Revises: 95cb2a021aa9
Create Date: 2023-11-10 22:32:00.080343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5141beedaf6c'
down_revision = '95cb2a021aa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finals',
    sa.Column('department', sa.VARCHAR(length=255), nullable=False),
    sa.Column('courseCode', sa.VARCHAR(length=255), nullable=False),
    sa.Column('section', sa.VARCHAR(length=255), nullable=False),
    sa.Column('room', sa.VARCHAR(length=255), nullable=False),
    sa.Column('dayOfWeek', sa.VARCHAR(length=255), nullable=False),
    sa.Column('day', sa.VARCHAR(length=255), nullable=False),
    sa.Column('hour', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('courseCode', 'section')
    )
    op.add_column('professor', sa.Column('name', sa.VARCHAR(length=255), nullable=True))
    op.add_column('professor', sa.Column('portfolio_page', sa.VARCHAR(length=255), nullable=True))
    op.add_column('professor', sa.Column('title', sa.VARCHAR(length=255), nullable=True))
    op.create_foreign_key(None, 'professor', 'course', ['classes'], ['crn'])
    op.drop_column('professor', 'last_name')
    op.drop_column('professor', 'first_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professor', sa.Column('first_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('professor', sa.Column('last_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'professor', type_='foreignkey')
    op.drop_column('professor', 'title')
    op.drop_column('professor', 'portfolio_page')
    op.drop_column('professor', 'name')
    op.drop_table('finals')
    # ### end Alembic commands ###
