"""<message>

Revision ID: 3b03a0336c68
Revises: 59f3440d3adb
Create Date: 2024-10-15 20:43:55.333043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b03a0336c68'
down_revision = '59f3440d3adb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('admin', sa.BOOLEAN(), nullable=True))
    op.add_column('test', sa.Column('enable', sa.BOOLEAN(), nullable=True))
    op.add_column('test', sa.Column('super_admin', sa.BOOLEAN(), nullable=True))
    op.alter_column('user_account', 'password',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_account', 'password',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('test', 'super_admin')
    op.drop_column('test', 'enable')
    op.drop_column('test', 'admin')
    # ### end Alembic commands ###
