"""Add course watch table

Revision ID: 9905ff4f7f18
Revises: ef478711822e
Create Date: 2024-04-12 20:36:30.208020

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9905ff4f7f18'
down_revision = 'ef478711822e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_watch',
    sa.Column('crn', sa.VARCHAR(length=255), nullable=False),
    sa.Column('watchers', postgresql.ARRAY(sa.INTEGER()), nullable=True),
    sa.PrimaryKeyConstraint('crn')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_watch')
    # ### end Alembic commands ###
