"""semester course foreign key

Revision ID: 032a3a88b6d2
Revises: c959c263997f
Create Date: 2024-11-01 21:24:08.801806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '032a3a88b6d2'
down_revision = '6c9a1ffc58a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('professor', sa.VARCHAR(length=255), nullable=True))
    op.add_column('course', sa.Column('semester_id', sa.VARCHAR(length=255), nullable=True))
    op.create_foreign_key(None, 'course', 'semester_info', ['semester_id'], ['semester'], ondelete='CASCADE')
    op.drop_column('course', 'semester')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('semester', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.drop_column('course', 'semester_id')
    op.drop_column('course', 'professor')
    # ### end Alembic commands ###
