"""testing finals

Revision ID: d48640fdbd48
Revises: c959c263997f
Create Date: 2024-04-02 20:17:51.135402

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd48640fdbd48'
down_revision = 'c959c263997f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finals',
    sa.Column('crn', sa.VARCHAR(length=255), nullable=False),
    sa.Column('department', sa.VARCHAR(length=255), nullable=True),
    sa.Column('level', sa.INTEGER(), nullable=True),
    sa.Column('section', sa.VARCHAR(length=255), nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), nullable=True),
    sa.Column('full_title', sa.TEXT(), nullable=True),
    sa.Column('location', sa.TEXT(), nullable=True),
    sa.Column('day', sa.INTEGER(), nullable=True),
    sa.Column('start_time', postgresql.TIME(), nullable=True),
    sa.Column('end_time', postgresql.TIME(), nullable=True),
    sa.PrimaryKeyConstraint('crn')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('finals')
    # ### end Alembic commands ###
