"""<update_user_account>

Revision ID: fe8dda9eb8e6
Revises: 3b03a0336c68
Create Date: 2024-10-15 21:24:51.417230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe8dda9eb8e6'
down_revision = '3b03a0336c68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('user_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('password', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('major', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('degree', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('admin', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('enable', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('super_admin', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='test_pkey'),
    sa.UniqueConstraint('email', name='test_email_key')
    )
    # ### end Alembic commands ###
