"""semester course relationship

Revision ID: f62dd5e95906
Revises: 032a3a88b6d2
Create Date: 2024-11-05 21:04:15.417023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f62dd5e95906'
down_revision = '032a3a88b6d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('semester', sa.VARCHAR(length=255), nullable=True))
    op.drop_constraint('course_semester_id_fkey', 'course', type_='foreignkey')
    op.create_foreign_key(None, 'course', 'semester_info', ['semester'], ['semester'], ondelete='CASCADE')
    op.drop_column('course', 'semester_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('semester_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.create_foreign_key('course_semester_id_fkey', 'course', 'semester_info', ['semester_id'], ['semester'], ondelete='CASCADE')
    op.drop_column('course', 'semester')
    # ### end Alembic commands ###
