"""adding finals

Revision ID: 1ff4f05483ad
Revises: 6c9a1ffc58a5
Create Date: 2024-10-15 21:38:59.576120

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6c9a1ffc58a5'
down_revision = 'c959c263997f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('final',
    sa.Column('semester', sa.VARCHAR(length=255), nullable=False),
    sa.Column('course', sa.VARCHAR(length=255), nullable=False),
    sa.Column('section', sa.INTEGER(), nullable=False),
    sa.Column('start', postgresql.TIME(), nullable=True),
    sa.Column('end', postgresql.TIME(), nullable=True),
    sa.Column('room_assignment', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('course', 'section', 'semester', 'room_assignment')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('final')
    # ### end Alembic commands ###
