"""<message>

Revision ID: 59f3440d3adb
Revises: c61849c08ba7
Create Date: 2024-10-04 20:00:32.725936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59f3440d3adb'
down_revision = 'c61849c08ba7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_account', 'password',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_account', 'password',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
