/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/pagenotfound': RouteRecordInfo<'/pagenotfound', '/:path(.*)*', Record<never, never>, Record<never, never>>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/admin': RouteRecordInfo<'/admin', '/admin', Record<never, never>, Record<never, never>>,
    '/explore': RouteRecordInfo<'/explore', '/explore', Record<never, never>, Record<never, never>>,
    '/explore/[major]': RouteRecordInfo<'/explore/[major]', '/explore/:major', { major: ParamValue<true> }, { major: ParamValue<false> }>,
    '/finals': RouteRecordInfo<'/finals', '/finals', Record<never, never>, Record<never, never>>,
    '/pathways': RouteRecordInfo<'/pathways', '/pathways', Record<never, never>, Record<never, never>>,
    '/professors': RouteRecordInfo<'/professors', '/professors', Record<never, never>, Record<never, never>>,
  }
}
