name: PR CI/CD

on:
  push:
  workflow_dispatch:

jobs:
  backend-unit-tests:
    name: Run backend unit tests
    runs-on: ubuntu-18.04
    timeout-minutes: 5
    container: python:3.8

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: yacs
        ports:
          - 5432/tcp
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r src/api/requirements.txt -r tests/requirements.txt

      - name: Setup database
        env:
          DB_PORT: 5432
          DB_USER: postgres
          DB_PASS: postgres
          DB_NAME: yacs
          DB_HOST: postgres
        working-directory: src/api
        run: |
          python tables/database_session.py && PYTHONPATH=. alembic upgrade head

      - name: Run unit tests with coverage
        env:
          DB_PORT: 5432
          DB_USER: postgres
          DB_PASS: postgres
          DB_NAME: yacs
          DB_HOST: postgres
          TEST_CSV: rpi_data/summer-2020.csv
        run: |
          bash scripts/test.sh

  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Build and Run Production
        run: |
          docker-compose \
            -f docker-compose.yml \
            -f docker-compose.production.yml \
            build &&
          docker-compose \
            -f docker-compose.yml \
            -f docker-compose.production.yml \
            up -d

      - name: Seed test data
        working-directory: rpi_data
        run: |
          function load_semester() {
              curl \
                  --insecure \
                  --location \
                  --request POST \
                  'https://localhost/api/bulkCourseUpload' \
                  --form "file=@$1" \
                  --form 'isPubliclyVisible=true' \
                  --max-time 60 \
                  -v
          }
          load_semester "summer-2021.csv"
          load_semester "fall-2021.csv"

      - name: run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.7.x
          lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{secrets.LHCI_GITHUB_APP_TOKEN}}

  publish-action-status:
    needs: [backend-unit-tests, lhci]
    if: always()
    runs-on: ubuntu-latest

    steps:
      - uses: technote-space/workflow-conclusion-action@v1
      - name: Publish status checks
        uses: LouisBrunner/checks-action@v0.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: CI
          conclusion: ${{ env.WORKFLOW_CONCLUSION }}

  temp_deploy:
    needs: [backend-unit-tests, lhci]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 13.x
        uses: actions/setup-node@v1
        with:
          node-version: 13.x

      - name: echo env (for info)
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo $GITHUB_HEAD_REF)"
          echo "##[set-output name=datetime_ready;]$(TZ='America/New_York' date --date '10 minutes')"
        id: info

      - name: Provision Infrastructure
        run: |
          cd ops/
          npm install
          node provision.js | tee out.txt
          echo "##[set-output name=link;]$(cat out.txt | grep http)"
        env:
          LINODE_TOKEN: ${{ secrets.LINODE_TOKEN }}
          SERVER_ROOT_PASS: ${{ secrets.SERVER_ROOT_PASS }}
          SSH_PUB_KEYS: ${{ secrets.SSH_PUB_KEYS }}
          ACTIVE_SERVER_COUNT: ${{ secrets.ACTIVE_SERVER_COUNT }} # amount of vms to keep in the active queue
          BRANCH: ${{ steps.info.outputs.branch }}
        id: provision

      - name: Share Link on PR
        uses: vinodsai-a/actions-comment-pull-request@master
        with:
          message: |
            Deploy Link: ${{ steps.provision.outputs.link }}/
            Branch and Build Info: ${{ steps.provision.outputs.link }}:3000/info.txt
            Expected Time Ready: ${{ steps.info.outputs.datetime_ready }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
